---
title: "Predictions of Rapid Cystic Fibrosis Lung Disease Progression Informed by Socioeconomic Deprivation and Traffic-Related Air Pollution Exposure"
subtitle: "Geomarkers' total effects: Hamilton County"
author: "Grace C. Zhou"
date:   'Update: `r format(Sys.Date(), "%B %d, %Y")`'
header-includes:
   - \usepackage{bbm}
output:
  html_document: 
    df_print: paged
#    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: TRUE
    fig_caption: yes
    theme: flatly
bibliography: ECAT_refs.bib
link-citations: yes
---

```{r setup,echo=FALSE,warning = FALSE, message= FALSE}

knitr::opts_chunk$set(cache = FALSE, echo=FALSE, 
                      warning = FALSE, message= FALSE)

library(rmarkdown)
library(dplyr)
library(tmap)
library(leaflet)

indata <- readRDS('DATA/Hamilton_Data.rds')
ZipCode <- readRDS('DATA/Hamilton_Zipcode.rds')

#Function
##Reference:https://rdrr.io/github/r-spatial/leafem/src/R/homebutton.R#sym-addZoomFullButton
addHomeButton <- function(map, ext, group = "layer",
                          position = 'bottomright', add = TRUE) {
  
  leafletHomeButtonDependencies <- function() {
    list(
      htmltools::htmlDependency(
        "HomeButton",
        '0.0.1',
        system.file("htmlwidgets/lib/HomeButton", package = "leafem"),
        script = c("home-button.js", 'easy-button-src.min.js'),
        stylesheet = 'home-button.css'
      ))
  }
  
  if (inherits(map, "mapview")) map <- mapview2leaflet(map)
  stopifnot(inherits(map, c("leaflet", "leaflet_proxy")))
  
  # drop names in case extent of sf object
  if (!missing(ext)) {
    if (inherits(ext, "Extent")) {
      ext = as.vector(ext)[c(1, 3, 2, 4)]
    } else {
      ext = as.vector(ext)
    }
    useext = TRUE
  } else {
    ext = c(0, 0, 0, 0)
    useext = FALSE
  }
  
  hb <- try(getCallEntryFromMap(map, "addHomeButton"), silent = TRUE)
  if (!inherits(hb, "try-error") & length(hb) == 1) {
    ext_coords <- unlist(map$x$calls[[hb]][["args"]][1:4])
    ext_map <- c(ext_coords[1], ext_coords[2], ext_coords[3], ext_coords[4])
    if (identical(ext, ext_map)) add = FALSE
  }
  
  if (add) {
    
    label <- paste("Zoom to Center")
    
    txt <- paste('<strong>', 'C', '</strong>')
    
    map$dependencies <- c(map$dependencies, leafletHomeButtonDependencies())
    leaflet::invokeMethod(map, leaflet::getMapData(map), 'addHomeButton',
                          ext[1],ext[2],ext[3],ext[4],
                          useext, group, label, txt, position)
  }
  
  else map
  
}


```

# Introduction

This plot was generated by the subset data for Hamilton County ONLY with a total of `r nrow(indata)` observations.

# Early Age (12.9 years old)

```{r early}

CountyData=indata %>% select(.,starts_with("early"),drive_time) %>%
  mutate(ECAT=round(early_eff_ecat,2),
         `Deprivation Index`=round(early_eff_depind,2),
         Green=round(early_eff_green,2),
         Drive=paste0(round(early_eff_drive,2), '(', drive_time,' mins)'),
         Overall=round(early_eff_total,2)) 


limit=range(indata$early_eff_total,indata$middle_eff_total,indata$late_eff_total,
            indata$early_eff_ecat,indata$middle_eff_ecat,indata$late_eff_ecat,
            indata$early_eff_depind,indata$middle_eff_depind,indata$late_eff_depind,
            indata$early_eff_green,indata$middle_eff_green,indata$late_eff_green,
            indata$early_eff_drive,indata$middle_eff_drive,indata$late_eff_drive)

Breaks=seq(from=limit[1],to=limit[2],length.out=5)

tmap_mode("view")
map.early <- tm_basemap('CartoDB.Positron') +
  tm_shape(CountyData) +
  tm_polygons(col = 'Overall', palette = "RdYlGn", midpoint=NA,breaks=Breaks,
              border.col = 'white',interactive = TRUE, style = "cont", alpha=0.5,
              border.alpha = 0.7,lwd = .1, id='Overall',
              popup.vars=c('ECAT'='ECAT',
                           'Dep. Index'='Deprivation Index',
                           'Green'='Green',
                           'Drive'='Drive'))+
  tm_shape(ZipCode)+
    tm_borders(col='dark gray')+
    tm_text('ZCTA5CE10',size=0.7)

   
map.early %>% 
  tmap_leaflet()  %>% 
  addHomeButton(group='CountyData',position='topleft') %>% 
   leaflet::addEasyButton(easyButton(
    icon='fa-crosshairs',title='Locate Me',
    onClick=JS('function(btn,map){map.locate({setView:true});}')))



```
********************************************************************************

# Middle Age (16.3 years old)

```{r middle}

CountyData=indata %>% select(.,starts_with("middle"),drive_time) %>%
  mutate(ECAT=round(middle_eff_ecat,2),
         `Deprivation Index`=round(middle_eff_depind,2),
         Green=round(middle_eff_green,2),
         Drive=paste0(round(middle_eff_drive,2), '(', drive_time,' mins)'),
         Overall=round(middle_eff_total,2))


tmap_mode("view")
map.middle <- tm_basemap('CartoDB.Positron') +
  tm_shape(CountyData) +
  tm_polygons(col = 'Overall', palette = "RdYlGn",midpoint=NA,
              breaks=Breaks,
              border.col = 'white',interactive = TRUE,style = "cont", alpha=0.5,
              border.alpha = 0.7,lwd = .1, id='Overall',
              popup.vars=c('ECAT'='ECAT',
                           'Dep. Index'='Deprivation Index',
                           'Green'='Green',
                           'Drive'='Drive'))+
  tm_shape(ZipCode)+
    tm_borders(col='dark gray')+
    tm_text('ZCTA5CE10',size=0.7)

   
map.middle %>% 
  tmap_leaflet()  %>% 
  addHomeButton(group='CountyData',position='topleft') %>% 
   leaflet::addEasyButton(easyButton(
    icon='fa-crosshairs',title='Locate Me',
    onClick=JS('function(btn,map){map.locate({setView:true});}')))


```
********************************************************************************

# Late Age (18.5 years old)

```{r late}

CountyData=indata %>% select(.,starts_with("late"),drive_time) %>%
  mutate(ECAT=round(late_eff_ecat,2),
         `Deprivation Index`=round(late_eff_depind,2),
         Green=round(late_eff_green,2),
         Drive=paste0(round(late_eff_drive,2), '(', drive_time,' mins)'),
         Overall=round(late_eff_total,2))


tmap_mode("view")
map.late <- tm_basemap('CartoDB.Positron') +
  tm_shape(CountyData) +
  tm_polygons(col = 'Overall', palette = "RdYlGn",midpoint=NA,
              breaks=Breaks,
              border.col = 'white',interactive = TRUE,style = "cont", alpha=0.5,
              border.alpha = 0.7,lwd = .1, id='Overall',
              popup.vars=c('ECAT'='ECAT',
                           'Dep. Index'='Deprivation Index',
                           'Green'='Green',
                           'Drive'='Drive'))+
  tm_shape(ZipCode)+
    tm_borders(col='dark gray')+
    tm_text('ZCTA5CE10',size=0.7)

   
map.late %>% 
  tmap_leaflet()  %>% 
  addHomeButton(group='CountyData',position='topleft') %>% 
   leaflet::addEasyButton(easyButton(
    icon='fa-crosshairs',title='Locate Me',
    onClick=JS('function(btn,map){map.locate({setView:true});}')))


```
********************************************************************************

# Notes

* This .html file was executed by R version 4.0.2 (2020-06-22)[@r_r_2020] with R package **tmap V3.3-2**[@tennekes_tmap_2018], **rmarkdown V2.9**[@allaire_rmarkdown_2021], **dplyr V1.0.5**[@wickham_dplyr_2021], **leaflet V2.0.4.1**[@cheng_leaflet_2021]. 

# References


